canonifyURLs = false

baseurl = ""
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "Sébastien Beauchamp"
theme = "sbdesigner"
disableLanguages = ["en"]

disableKinds = ["taxonomyTerm"]

[taxonomies]
    category = "categories"
    tag = "tags"

[languages]
  [languages.fr]
    title = "Sébastien Beauchamp"
    subtitle = "Expériences numériques & identité de marque"
    description="Je crois que les marques et les projets qui construisent une expérience intuitive, agréable et empathique réussissent à se démarquer."
    weight = 1
    languageName = "Fr"